ohmyzsh_users:
  - username: vagrant
    usergroup: vagrant
    home: /home/vagrant

ohmyzsh_plugins: git colored-man-page colorize extract history npm symfony2 httpie zsh-syntax-highlighting zsh-autosuggestions
